### ISSUE TITLE
Master Checklist

### ISSUE THREAD

**Issue by devinleonhart** [devinleonhart/blackbook#1]
The Black Book will be handled as a professional software project, with appropriate planning, documentation, testing, and deployment strategies. This project is for the education of myself and @aaronpflaumer on best software principles and rounding out our skillsets to become full-stack developers.

- [x] Build Requirements Documentation
- [x] Plan models and ERD
- [x] Plan UI and intended workflows.
- [x] Research & Implement technology stack
- [x] Implement deployment strategy
- [x] Implement testing framework
- [x] Create Readme for other devs
- [ ] Finish Minimum Viable Product
- [ ] Color / Design

**Comment by devinleonhart** [comment]
Moving to actual project tracking tools.
